import { creditCardPaymentEnabled } from "../NewContractMember/paymentMethods"

export const buildInitialValues = (language) => ({
  cups: "",
  cups_valid: false,
  social_tariff: false,
  tariff_name: "",
  tariff_type: "",
  has_member: "",
  member_is_holder: undefined,
  previous_holder: undefined,
  voluntary_donation: undefined,
  especial_cases: undefined,
  supply_point: {
    cnae: "9820",
    supply_point_accepted: false,
    attachments_reason_death: [],
    attachments_reason_merge: [],
    attachments_reason_electrodep: [],
    attachments_reason_electrodep_census: [],
    verified: false,
  },
  supply_point_address: "",
  address: {
    street: "",
    number: "",
    floor: "",
    door: "",
    stairs: "",
    bloc: "",
    postal_code: "",
    state: { id: "", name: "" },
    city: { id: "", name: "" },
  },
  member: {
    number: "",
    nif: "",
  },
  new_member: {
    nif: "",
    nif_valid: false,
    person_type: "",
    proxynif: "",
    proxyname: "",
    name: "",
    surname1: "",
    surname2: "",
    gender: "",
    birthdate: undefined,
    email: "",
    email2: "",
    phone: "",
    phone_code: "+34",
    phone_valid: false,
    language: `${language}_ES`,
    referral_source: "",
    payment_method: creditCardPaymentEnabled ? undefined : "iban",
    sepa_accepted: false,
    payment_authorization_accepted: false,
    iban: undefined,
    legal_person_accepted: false,
  },
  contract: {
    power: {
      power1: "1",
      power2: "2",
      power3: "3",
      power4: "",
      power5: "",
      power6: "",
    },
    phase: "mono",
  },
  privacy_policy_accepted: false,
  generic_conditions_accepted: false,
  statutes_accepted: false,
  comercial_info_accepted: false,
})
