name: Check for Outdated NPM Dependencies
on: [push]

jobs:
  check-outdated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: npm install

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      # Optional: Clear npm cache to prevent cache-related issues
      - name: Clear npm cache
        run: npm cache clean --force

      # Run npm outdated and handle failures
      - name: Check outdated dependencies
        run: |
          OUTDATED=$(npm outdated)
          if [[ -n "$OUTDATED" ]]; then
            echo "Outdated dependencies found!"
            echo "$OUTDATED"
            exit 1
          else
            echo "All dependencies are up-to-date."
          fi
