name: cypress webforms-ui
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install npm dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
