# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '20'

    name: Node ${{ matrix.node-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          #make ui-deploy
          npm install
          npm install coveralls --save-dev

      - name: Unit tests
        run: |
          #make testsa
          npm run test

      - name: Notify
        uses: Som-Energia/ghactions-notify@main
        if: always()
        with:
          webhook: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}

